VISITS = "visits AS v"
WEBSITES = "websites AS w"
USERS = "users AS u"
GROUPS = "groups AS g"
USER_GROUPS = "user_groups AS ug"
GROUP_VISIBILITY = "group_visibility AS gv"
HIDDEN_TAGS = "hidden_tags AS ht"
TAGS = "tags AS t"
COMMENTS = "comments AS c"
METADATA = "metadata AS m"
ATTRIBUTES = "attributes AS a"
MEDIA = "media AS me"
TRACKING = "tracking AS tr"
LINKS = "links AS l"
QUERIES = "queries AS q"

WEBSITE_TO_QUERY = "w.website_id = q.website_id"
ATTRIBUTE_TO_METADATA = "a.attribute_id = m.attribute_id"
VISIT_TO_METADATA = "v.visit_id = m.visit_id"

VISIT_ID = "v.visit_id"
